cmake: set C standard to GNU C due to inline assembly usage
Standard ISO C does not have inline assembly support, but is a compiler extension. For compilers which default to ISO C, specify the use of GNU extensions to enable inline assembly.

Fixes compiler errors like this:

```
error: use of undeclared identifier 'asm'
```